<?php
namespace app\index2\controller;
use think\Controller;
use think\Db;
use app\api;
class Charge extends Online
{
    protected $sye_rate;
    protected $role_rate;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user_rate=Db::table('group_settle')
            ->alias('a')
            ->join('rate b','a.pay_id=b.pay_prot_id')
            ->field('a.*,b.settle_rate settle,b.extra_rate extra,b.pay_name')
            ->where('group_id',$this->user_id)
            ->where('user_lv','1')
            ->select();
    }

    public function index()
    {

        $pay_id=input('id',1);

        $rate=Db::table('group_settle')
            ->alias('a')
            ->join('rate b','a.pay_id=b.pay_prot_id')
            ->field('a.*,b.settle_rate settle,b.extra_rate extra,b.pay_name')
            ->where('pay_id',$pay_id)
            ->where('group_id',$this->user_id)
            ->select();
        $this->assign('user_rate',$this->user_rate);
        $this->assign('rate',$rate);
        $this->assign('pay_id',$pay_id);
        return $this->fetch('rate');
    }

    public function update(){
        $pay_id=input('id');
        $user_lv=input('user_lv/a');
        $settle=input('settle_rate/a');
        $extra=input('extra_rate')*100;
        $parent=input('parent',0)/100;
        $superior=input('superior',0)/100;

        if(empty($pay_id)){
            $this->returnMsg['message']='请选择修改通道';
            return $this->returnMsg;
        }
        if($parent<$superior){
            $this->returnMsg['message']='间接推广返利不能大于直属推广返利';
            return $this->returnMsg;
        }

        $pay_rate=Db::table('rate')
            ->where('pay_prot_id',$pay_id)
            ->find();







        $rate=Db::table('group_settle')
            ->where('group_id',$this->user_id)
            ->where('pay_id',$pay_id)
            ->where('user_lv',1)
            ->find();
        if(empty($rate)){
            $this->returnMsg['message']='个人费率未找到';
            return $this->returnMsg;
        }

        if(($parent+$superior) >($settle[0]/100-$rate['settle_rate']) ){
            $this->returnMsg['message']='推广取现返利不能大于自身分润值';
            return $this->returnMsg;
        }
        if($extra<$rate['extra_rate']){
            $this->returnMsg['message']="下属服务费不能低于自身服务费";
            return $this->returnMsg;
        }
        $res=Db::table('group_settle')
            ->where('group_id',$this->user_id)
            ->where('pay_id',$pay_id)
            ->where('user_lv',1)
            ->update([
                'parent'=>$parent,
                'superior'=>$superior
            ]);
        foreach($user_lv as $key=>$val){
            if($val==1){
                $this->returnMsg['message']="不能修改自身费率";
                return $this->returnMsg;
            }
            if($settle[$key]/100<$rate['settle_rate']){
                $this->returnMsg['message']="下属费率不能低于自身费率";
                return $this->returnMsg;
            }

            if(!empty($settle[$key+1]) && $settle[$key]/100>$settle[$key+1]/100){
                $this->returnMsg['message']="终端费率不能低于直属费率";
                return $this->returnMsg;
            }
            if($val==3 && $settle[$key]/100<$pay_rate['settle_rate']){
                $this->returnMsg['message']="终端费率不能低于平台终端费率".$pay_rate['settle_rate'];
                return $this->returnMsg;
            }



            $res=Db::table('group_settle')
                ->where('group_id',$this->user_id)
                ->where('pay_id',$pay_id)
                ->where('user_lv',$user_lv[$key])
                ->update([
                    'settle_rate'=>$settle[$key]/100,
                    'extra_rate'=>$extra,
                    'parent'=>$parent,
                    'superior'=>$superior
                ]);
//            if(!$res){
//                $this->returnMsg['message']="更新失败";
//                return $this->returnMsg;
//            }
        }


        $this->returnMsg['message']="更新成功";
        $this->returnMsg['status']=200;
//        /$this->returnMsg['url']=url('index');
        return $this->returnMsg;
    }



}
