<?php
namespace app\index2\controller;
use think\Controller;
use think\Model;
class Online extends Core
{
    protected $returnMsg;
    protected $user_id;
    protected $role_id;
    protected $sort='desc';
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user_id=session('merchant_id');
        $user_data=model('user')
            ->alias('a')
            ->join('role b',"a.role_id=b.role_id")
            ->field('a.user_id,a.role_id,b.role_name')
            ->where('a.user_id', $this->user_id)
            ->find();
        session('role_id',$user_data['role_id']);
        $this->role_id=session('role_id');
        if(empty($this->user_id)){
            $this->redirect('publics/index');
        }
    }


}
